function(enable_sanitizers project_name)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    if(PPR_ENABLE_COVERAGE)
      target_compile_options(${project_name} PRIVATE --coverage -O0 -g)
      target_link_libraries(${project_name} PRIVATE --coverage)
    endif()

    set(SANITIZERS "")

    if(PPR_ENABLE_SANITIZER_ADDRESS)
      list(APPEND SANITIZERS "address")
    endif()

    if(PPR_ENABLE_SANITIZER_LEAK)
      list(APPEND SANITIZERS "leak")
    endif()

    if(PPR_ENABLE_SANITIZER_UNDEFINED)
      list(APPEND SANITIZERS "undefined")
    endif()

    if(PPR_ENABLE_SANITIZER_THREAD)
      if("address" IN_LIST SANITIZERS OR "leak" IN_LIST SANITIZERS)
        message(WARNING "${project_name}: Thread sanitizer does not work with Address and Leak sanitizer enabled")
      else()
        list(APPEND SANITIZERS "thread")
      endif()
    endif()

    if(PPR_ENABLE_SANITIZER_MEMORY AND CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
      if("address" IN_LIST SANITIZERS OR "thread" IN_LIST SANITIZERS OR "leak" IN_LIST SANITIZERS)
        message(WARNING "${project_name}: Memory sanitizer does not work with Address, Thread or Leak sanitizer enabled")
      else()
        list(APPEND SANITIZERS "memory")
      endif()
    endif()

    list(JOIN SANITIZERS "," LIST_OF_SANITIZERS)

    if(LIST_OF_SANITIZERS)
      if(NOT "${LIST_OF_SANITIZERS}" STREQUAL "")
        target_compile_options(${project_name} PRIVATE -fsanitize=${LIST_OF_SANITIZERS})
        target_link_options(${project_name} PRIVATE -fsanitize=${LIST_OF_SANITIZERS})
      endif()
    endif()
  elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(SANITIZERS "")

    if(PPR_ENABLE_SANITIZER_ADDRESS)
      list(APPEND SANITIZERS "address")
    endif()

    if(PPR_ENABLE_SANITIZER_LEAK)
      message(STATUS "${project_name}: Leak sanitizer is not supported by MSVC")
    endif()
    if(PPR_ENABLE_SANITIZER_UNDEFINED)
      message(STATUS "${project_name}: UB sanitizer is not supported by MSVC")
    endif()
    if(PPR_ENABLE_SANITIZER_THREAD)
      message(STATUS "${project_name}: Thread sanitizer is not supported by MSVC")
    endif()
    if(PPR_ENABLE_SANITIZER_MEMORY)
      message(STATUS "${project_name}: Memory sanitizer is not supported by MSVC")
    endif()

    list(JOIN SANITIZERS "," LIST_OF_SANITIZERS)

    if(LIST_OF_SANITIZERS)
      if(NOT "${LIST_OF_SANITIZERS}" STREQUAL "")
        target_compile_options(${project_name} PRIVATE /fsanitize=${LIST_OF_SANITIZERS})
      endif()
    endif()
  endif()

  if(PPR_ENABLE_CLANG_TIDY)
    enable_clang_tidy(${project_name} ${PPR_WARNINGS_AS_ERRORS})
  endif()
endfunction()
